import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const createRoomWxmlPath = path.join(process.cwd(), "miniprogram/pages/create-room/create-room.wxml");
const createRoomWxssPath = path.join(process.cwd(), "miniprogram/pages/create-room/create-room.wxss");
const createRoomScriptPath = path.join(process.cwd(), "miniprogram/pages/create-room/create-room.js");

test("create room page keeps only the fixed 8-seat room summary plus live config options", () => {
  const wxml = fs.readFileSync(createRoomWxmlPath, "utf8");
  const wxss = fs.readFileSync(createRoomWxssPath, "utf8");
  const script = fs.readFileSync(createRoomScriptPath, "utf8");

  assert.match(script, /const app = getApp\(\);/);
  assert.match(script, /require\("\.\.\/\.\.\/utils\/room-themes"\)/);
  assert.match(script, /playerCount:\s*8/);
  assert.match(script, /devtoolsMode:\s*false/);
  assert.match(script, /app\.globalData && app\.globalData\.isDevtoolsMode/);
  assert.match(script, /ROOM_THEME_IDS/);
  assert.match(script, /roomThemeOptions:\s*buildThemeOptions\(\)/);
  assert.match(script, /themePreviewId:\s*DEFAULT_ROOM_THEME_ID/);
  assert.match(script, /const themePreviewId = normalizeRoomThemeId\(options && options\.themeId\)/);
  assert.match(script, /onSelectTheme\(event\)/);
  assert.doesNotMatch(script, /playerCountOptions/);
  assert.doesNotMatch(script, /allowSpectator/);
  assert.doesNotMatch(script, /lockRoom/);

  assert.match(wxml, /<text class="block-title">房间形式<\/text>/);
  assert.match(wxml, /create-page \{\{devtoolsMode \? 'is-perf-lite' : ''\}\}/);
  assert.match(wxml, /class="create-sheet"/);
  assert.match(wxml, /class="create-sheet__eyebrow">ROOM SETUP<\/text>/);
  assert.match(wxml, /class="create-sheet__title">创建房间<\/text>/);
  assert.match(wxml, /<scroll-view class="create-sheet__scroll" scroll-y="true"/);
  assert.match(wxml, /class="create-sheet__footer"/);
  assert.match(wxml, /class="room-form-card"/);
  assert.match(wxml, /class="room-form-card__badge">固定房间<\/view>/);
  assert.match(wxml, /class="room-form-card__title">固定 8 个座位<\/text>/);
  assert.match(wxml, /房间始终保留 8 个座位，来几个人算几个人，最多 8 人同局。/);
  assert.match(wxml, /<text class="block-title">房间主题<\/text>/);
  assert.match(wxml, /class="theme-picker"/);
  assert.match(wxml, /class="theme-card theme-card--\{\{item\.id\}\} \{\{themePreviewId === item\.id \? 'is-active' : ''\}\}"/);
  assert.match(wxml, /class="theme-card__check">已选<\/view>/);
  assert.match(wxml, /class="theme-card__preview"/);
  assert.match(wxml, /class="theme-card__title">\{\{item\.label\}\}<\/text>/);
  assert.match(wxml, /class="toggle-card__signal \{\{wildcardOneEnabled \? 'is-on' : 'is-off'\}\}"/);
  assert.match(wxml, /class="create-note-card"/);
  assert.match(wxml, /class="create-note-card create-note-card--experiment"/);
  assert.match(wxml, /class="create-actions"/);
  assert.doesNotMatch(wxml, /允许旁观/);
  assert.doesNotMatch(wxml, /锁定房间/);
  assert.doesNotMatch(wxml, /测试模式/);
  assert.doesNotMatch(script, /\btestMode:\s*false/);
  assert.match(script, /&testMode=0/);
  assert.match(script, /&themeId=\$\{themeId\}/);
  assert.doesNotMatch(script, /playerCount=\$\{/);
  assert.doesNotMatch(script, /allowSpectator=/);
  assert.doesNotMatch(script, /lockRoom=/);
  assert.match(script, /getCurrentPages/);
  assert.match(script, /wx\.switchTab\(\{ url: "\/pages\/lobby\/lobby" \}\)/);

  assert.match(wxss, /\.create-sheet\s*\{/);
  assert.match(wxss, /\.create-sheet\s*\{[\s\S]*display:\s*flex[\s\S]*flex-direction:\s*column/);
  assert.match(wxss, /\.create-sheet\s*\{[\s\S]*height:\s*min\(1320rpx,\s*calc\(100vh - env\(safe-area-inset-top\) - env\(safe-area-inset-bottom\) - 84rpx\)\)/);
  assert.match(wxss, /\.create-sheet__scroll\s*\{[\s\S]*flex:\s*1[\s\S]*min-height:\s*0/);
  assert.match(wxss, /\.create-sheet__footer\s*\{[\s\S]*flex:\s*0 0 auto/);
  assert.match(wxss, /\.create-page\s*\{[\s\S]*display:\s*flex[\s\S]*align-items:\s*flex-end[\s\S]*justify-content:\s*center/);
  assert.match(wxss, /\.create-sheet__glow--a\s*\{/);
  assert.match(wxss, /\.toggle-card__signal\.is-on\s*\{/);
  assert.match(wxss, /\.theme-picker\s*\{/);
  assert.match(wxss, /\.theme-picker\s*\{[\s\S]*display:\s*flex[\s\S]*align-items:\s*stretch/);
  assert.match(wxss, /\.theme-card\s*\{/);
  assert.match(wxss, /\.theme-card\s*\{[\s\S]*flex:\s*1 1 0[\s\S]*flex-direction:\s*column/);
  assert.match(wxss, /\.theme-card__check\s*\{/);
  assert.match(wxss, /\.theme-card--jade-green \.theme-card__preview\s*\{/);
  assert.match(wxss, /\.theme-card--ruby-red \.theme-card__preview\s*\{/);
  assert.match(wxss, /\.theme-card--imperial-red \.theme-card__preview\s*\{/);
  assert.match(wxss, /\.create-note-card\s*\{/);
  assert.match(wxss, /\.create-note-card--experiment\s*\{/);
  assert.match(wxss, /\.create-btn\s*\{/);
  assert.match(wxss, /\.room-form-card\s*\{/);
  assert.match(wxss, /\.room-form-card__title\s*\{/);
  assert.match(wxss, /\.room-form-card__desc\s*\{/);
  assert.match(wxss, /\.create-page\.is-perf-lite \.create-sheet,[\s\S]*animation:\s*none !important/);
  assert.match(wxss, /\.create-page\.is-perf-lite \.mask-bg,[\s\S]*display:\s*none !important/);
});
