import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const lobbyWxmlPath = path.join(process.cwd(), "miniprogram/pages/lobby/lobby.wxml");
const lobbyWxssPath = path.join(process.cwd(), "miniprogram/pages/lobby/lobby.wxss");
const lobbyJsonPath = path.join(process.cwd(), "miniprogram/pages/lobby/lobby.json");
const customTabBarWxmlPath = path.join(process.cwd(), "miniprogram/custom-tab-bar/index.wxml");
const customTabBarWxssPath = path.join(process.cwd(), "miniprogram/custom-tab-bar/index.wxss");

test("lobby keeps a fixed full-screen hero with create and join as the primary actions", () => {
  const wxml = fs.readFileSync(lobbyWxmlPath, "utf8");
  const wxss = fs.readFileSync(lobbyWxssPath, "utf8");
  const tabWxml = fs.readFileSync(customTabBarWxmlPath, "utf8");
  const tabWxss = fs.readFileSync(customTabBarWxssPath, "utf8");
  const json = JSON.parse(fs.readFileSync(lobbyJsonPath, "utf8"));

  assert.match(wxml, /<view class="lobby-shell">/);
  assert.match(wxml, /<view class="hero-zone">/);
  assert.match(wxml, /class="home-logo-mask"/);
  assert.match(wxml, /class="home-logo"[\s\S]*mode="aspectFill"/);
  assert.match(wxml, /class="hero-profile-card" bindtap="goProfile"/);
  assert.match(wxml, /class="hero-profile-card__title">编号 \{\{profileDisplayNo\}\}<\/text>/);
  assert.match(wxml, /class="hero-profile-card__sub">查看个人主页<\/text>/);
  assert.match(wxml, /<view class="lobby-main">/);
  assert.match(wxml, /class="glass-card create-room-card"/);
  assert.match(wxml, /class="login-gate__eyebrow">ACCOUNT GATE<\/text>/);
  assert.doesNotMatch(wxml, /class="create-modal"/);
  assert.doesNotMatch(wxml, /closeCreateRoomSheet/);
  assert.match(wxml, /class="glass-card join-card"/);
  assert.match(wxml, /class="join-card__title">加入房间<\/text>/);
  assert.match(wxml, /class="join-card__sub">输入房间号，快速加入<\/text>/);
  assert.match(wxml, /placeholder="输入房间号"/);
  assert.match(wxml, /<text class="hero-title">满上，<\/text>/);
  assert.match(wxml, /<text class="hero-title">来一局<\/text>/);
  assert.doesNotMatch(wxml, /class="glass-card profile-card"/);
  assert.doesNotMatch(wxml, /<view class="bottom-action">/);
  assert.doesNotMatch(wxml, /创建新局/);
  assert.doesNotMatch(wxml, /玩家001/);
  assert.doesNotMatch(wxml, /<scroll-view class="lobby-body-scroll"/);
  assert.doesNotMatch(wxml, /status-row/);
  assert.doesNotMatch(wxml, /status-right/);
  assert.doesNotMatch(wxml, /status-signal/);

  assert.equal(json.disableScroll, true);
  assert.match(wxss, /page\s*\{[\s\S]*height:\s*100%[\s\S]*overflow:\s*hidden/);
  assert.match(wxss, /\.lobby-page\s*\{[\s\S]*height:\s*100%/);
  assert.match(wxss, /\.lobby-page\s*\{[\s\S]*overflow:\s*hidden/);
  assert.match(wxss, /\.lobby-shell\s*\{[\s\S]*display:\s*flex[\s\S]*flex-direction:\s*column/);
  assert.match(wxss, /\.lobby-shell\s*\{[\s\S]*padding:\s*0\s+26rpx\s+calc\(140rpx \+ env\(safe-area-inset-bottom\)\)/);
  assert.match(wxss, /\.hero-zone\s*\{[\s\S]*flex-shrink:\s*0/);
  assert.match(wxss, /\.hero-zone\s*\{[\s\S]*height:\s*468rpx[\s\S]*margin-left:\s*-26rpx[\s\S]*margin-right:\s*-26rpx/);
  assert.match(wxss, /\.home-logo-mask\s*\{[\s\S]*left:\s*18rpx[\s\S]*top:\s*118rpx[\s\S]*width:\s*468rpx[\s\S]*height:\s*298rpx[\s\S]*overflow:\s*hidden/);
  assert.match(wxss, /\.hero-profile-card\s*\{[\s\S]*right:\s*22rpx[\s\S]*top:\s*252rpx[\s\S]*width:\s*260rpx/);
  assert.match(wxss, /\.hero-profile-card__avatar\s*\{[\s\S]*border:\s*3rpx solid rgba\(255,\s*80,\s*151,\s*0\.9\)/);
  assert.match(wxss, /\.lobby-main\s*\{[\s\S]*flex:\s*1/);
  assert.match(wxss, /\.lobby-main\s*\{[\s\S]*margin-top:\s*-6rpx/);
  assert.match(wxss, /\.panel-stack\s*\{[\s\S]*gap:\s*44rpx/);
  assert.match(wxss, /\.create-room-card\s*\{[\s\S]*min-height:\s*324rpx[\s\S]*padding:\s*58rpx 50rpx/);
  assert.match(wxss, /\.login-gate__sheet\s*\{[\s\S]*bottom:\s*0[\s\S]*border-radius:\s*42rpx 42rpx 0 0/);
  assert.match(wxss, /@keyframes login-gate-sheet-in/);
  assert.match(wxss, /\.join-card\s*\{[\s\S]*flex-direction:\s*column[\s\S]*min-height:\s*238rpx/);
  assert.match(wxml, /class="join-input-shell"[\s\S]*class="join-input"/);
  assert.match(wxml, /wx:for="\{\{joinRoomDigits\}\}"[\s\S]*join-code-board__cell--\{\{item\.tone\}\} \{\{item\.value \? 'is-filled' : ''\}\}/);
  assert.match(wxss, /\.join-card__row\s*\{[\s\S]*display:\s*flex[\s\S]*border:\s*1rpx solid rgba\(218,\s*183,\s*111,\s*0\.22\)/);
  assert.match(wxss, /\.join-input-shell\s*\{[\s\S]*overflow:\s*visible/);
  assert.match(wxss, /\.join-code-board__cell--gold\s*\{[\s\S]*border-color:\s*rgba\(226,\s*178,\s*86,\s*0\.34\)/);
  assert.match(wxss, /\.join-code-board__cell--green\.is-filled\s*\{[\s\S]*border-color:\s*rgba\(255,\s*225,\s*148,\s*0\.58\)/);
  assert.match(wxss, /\.join-code-board__cell--gold\.is-filled\s*\{[\s\S]*border-color:\s*rgba\(255,\s*221,\s*139,\s*0\.62\)/);
  assert.match(tabWxml, /class="tab-notch"/);
  assert.match(tabWxml, /class="tab-center-dice" src="\/assets\/tab-dice\.png"/);
  assert.doesNotMatch(tabWxml, /class="dice-cube"/);
  assert.doesNotMatch(tabWxml, /tab-center-ball__die/);
  assert.match(tabWxss, /\.tab-shell\s*\{[\s\S]*bottom:\s*calc\(22rpx \+ env\(safe-area-inset-bottom\)\)[\s\S]*justify-content:\s*center/);
  assert.match(tabWxss, /\.tab-inner\s*\{[\s\S]*width:\s*636rpx[\s\S]*height:\s*96rpx[\s\S]*border-radius:\s*34rpx/);
  assert.match(tabWxss, /\.tab-inner::before\s*\{[\s\S]*top:\s*-38rpx[\s\S]*width:\s*148rpx[\s\S]*background:\s*rgba\(13,\s*10,\s*30,\s*0\.98\)[\s\S]*border:\s*0/);
  assert.match(tabWxss, /\.tab-notch\s*\{[\s\S]*top:\s*-31rpx[\s\S]*width:\s*120rpx[\s\S]*box-shadow:\s*none/);
  assert.match(tabWxss, /\.tab-center\s*\{[\s\S]*margin-top:\s*-48rpx/);
  assert.match(tabWxss, /\.tab-center-ball\s*\{[\s\S]*width:\s*92rpx[\s\S]*border:\s*8rpx solid #a94aff/);
  assert.match(tabWxss, /\.tab-center-dice\s*\{[\s\S]*width:\s*60rpx[\s\S]*height:\s*60rpx/);
});
