import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const roomWxmlPath = path.join(process.cwd(), "miniprogram/pages/room/room.wxml");
const roomWxssPath = path.join(process.cwd(), "miniprogram/pages/room/room.wxss");
const roomJsPath = path.join(process.cwd(), "miniprogram/pages/room/room.js");

test("room call signals stay on seats while self last-call hints stay removed", () => {
  const roomWxml = fs.readFileSync(roomWxmlPath, "utf8");
  const roomWxss = fs.readFileSync(roomWxssPath, "utf8");
  const roomJs = fs.readFileSync(roomJsPath, "utf8");

  assert.doesNotMatch(roomWxml, /class="table-call"/);
  assert.doesNotMatch(roomWxml, /class="seat__meta-chip/);
  assert.doesNotMatch(roomWxml, /class="room-self__meta"/);
  assert.doesNotMatch(roomWxml, /class="room-self-call-hint room-self-call-hint--floating"/);
  assert.doesNotMatch(roomWxml, /class="room-self-call-hint room-self-call-hint--inline"/);
  assert.doesNotMatch(roomWxml, /class="table-call/);
  assert.doesNotMatch(roomWxml, /class="room-callbar/);
  assert.doesNotMatch(roomWxml, /class="room-self__last-call"/);
  assert.doesNotMatch(roomWxml, /class="room-self__meta-row"/);
  assert.doesNotMatch(roomWxss, /\.seat__meta-chip\s*\{/);
  assert.doesNotMatch(roomWxss, /\.room-self__meta\s*\{/);
  assert.doesNotMatch(roomWxss, /\.room-self-call-hint(?:--floating|--inline)?\s*\{/);
  assert.doesNotMatch(roomWxss, /\.table-call\s*\{/);
  assert.doesNotMatch(roomWxss, /\.room-callbar\s*\{/);
  assert.doesNotMatch(roomWxss, /\.room-self__last-call\s*\{/);
  assert.doesNotMatch(roomWxss, /\.room-self__meta-row\s*\{/);
  assert.doesNotMatch(roomJs, /\bselfScoreText\b/);
  assert.doesNotMatch(roomJs, /\bselfCallHint\b/);
  assert.doesNotMatch(roomJs, /\bFIGMA_SCORE_FALLBACKS\b/);
  assert.doesNotMatch(roomJs, /\bresolvePlayerScoreText\b/);
  assert.doesNotMatch(roomJs, /\bbadgeClass\b/);
  assert.doesNotMatch(roomJs, /\bscoreText\b/);
  assert.doesNotMatch(roomJs, /\bcurrentPlayerShort\b/);
  assert.doesNotMatch(roomJs, /\blastCallText\b/);
  assert.doesNotMatch(roomJs, /\bhasLastCall\b/);
  assert.doesNotMatch(roomJs, /\bopenHintText\b/);
  assert.doesNotMatch(roomJs, /\bstagePrimaryText\b/);
  assert.doesNotMatch(roomJs, /\bstageSecondaryText\b/);
  assert.doesNotMatch(roomJs, /\bstageDiceText\b/);
  assert.doesNotMatch(roomJs, /\bstageCallMain\b/);
  assert.doesNotMatch(roomJs, /\bstageCallSub\b/);
  assert.doesNotMatch(roomJs, /\bstageCallTicker\b/);
  assert.doesNotMatch(roomJs, /\bstageCallCount\b/);
  assert.doesNotMatch(roomJs, /\bstageCallPoint\b/);
  assert.doesNotMatch(roomJs, /\bstageCallPointAsset\b/);
  assert.doesNotMatch(roomJs, /\bstageCallBy\b/);
  assert.doesNotMatch(roomJs, /\bstageCallBump\b/);
  assert.doesNotMatch(roomJs, /\bstageShowProgress\b/);
  assert.doesNotMatch(roomJs, /\bstageResultVisible\b/);
  assert.doesNotMatch(roomJs, /\bstageWinnerText\b/);
  assert.doesNotMatch(roomJs, /\bstageDeclaredText\b/);
  assert.doesNotMatch(roomJs, /\bstageActualText\b/);
  assert.doesNotMatch(roomJs, /\bphaseText\b/);
  assert.doesNotMatch(roomJs, /\bopenResultText\b/);
  assert.doesNotMatch(roomJs, /\bpublicDiceText\b/);
  assert.doesNotMatch(roomJs, /\bpublicDiceList\b/);
  assert.doesNotMatch(roomJs, /\bphaseToText\b/);
  assert.doesNotMatch(roomJs, /\bopenButtonText\b/);
  assert.doesNotMatch(roomJs, /\bstartButtonText\b/);
  assert.doesNotMatch(roomJs, /\bcanStart\b/);
  assert.doesNotMatch(roomJs, /\bfeaturedPlayerName\b/);
  assert.doesNotMatch(roomJs, /\bfeaturedPlayerAvatar\b/);
  assert.doesNotMatch(roomJs, /\bfeaturedPlayerInitial\b/);
  assert.doesNotMatch(roomJs, /\bhideSocialUi\b/);
  assert.doesNotMatch(roomJs, /const currentPlayer = /);
  assert.doesNotMatch(roomJs, /\bclockText\b/);
  assert.doesNotMatch(roomJs, /\bshowDebug\b/);
  assert.doesNotMatch(roomJs, /调试日志/);
  assert.doesNotMatch(roomJs, /\bselfLastCallText\b/);
  assert.match(roomJs, /\bbuildCallEventKey\b/);
  assert.match(roomWxss, /\.seat__bubble\.latest\s*\{/);
  assert.match(roomWxss, /\.seat__bubble\.latest::after\s*\{/);
  assert.doesNotMatch(roomJs, /\bcallAttentionKey\b/);
  assert.doesNotMatch(roomJs, /\barmCallAttentionClear\b/);
  assert.doesNotMatch(roomWxss, /\.seat__bubble\.fresh\s*\{/);
  assert.doesNotMatch(roomWxss, /@keyframes room-call-bubble-pulse/);
});
